version = 0.1

[default.deploy.parameters]
stack_name = "prism-services-prod"
resolve_s3 = true
s3_prefix = "prism-services-prod"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"master\" AlertEmail=\"dom@productradars.com\" DailyAiLimit=\"150\" BedrockModelId=\"anthropic.claude-3-haiku-20240307-v1:0\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
