import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { Amplify } from 'aws-amplify'
// @ts-ignore - This file is generated by `npx ampx sandbox`
import outputs from '../amplify_outputs.json'
import '@aws-amplify/ui-react/styles.css'
import './index.css'
import App from './App.tsx'

Amplify.configure(outputs)

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
